name: Snyk Demo Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Snyk Open Source scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects || true
      - name: Snyk Code scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test || true
